### ISSUE TITLE
Testing this package with different versions of GAP and packages

### ISSUE THREAD

**Issue by alex-konovalov** [FriedrichRober/LINS#21]
Hello, nice to learn about your package at https://math.stackexchange.com/questions/3697546/finding-low-index-normal-subgroups-of-finitely-presented-groups-in-gap/3699244#3699244 and see that you're using CI.

Since this package provides a standard test, I suggest to add it to the two tests that we offer to GAP package authors to test _development_ versions of their packages for compatibility with GAP stable and master branches, and with other stable or newest GAP packages:
- https://github.com/gap-infra/gap-docker-pkg-tests-master-devel 
- https://github.com/gap-infra/gap-docker-pkg-tests-stable-4.11-devel

The first of these two repositories has a README file with further details. To add your package to the test, please submit a pull request to add a line to the `.travis.yml` file.

**Comment by FriedrichRober** [comment]
This sounds like a great idea. I will submit the pull requests, but I have a question reguarding this standard test.

I need the package `grape` for some tests in my package. From where would this information be pulled by this standard test?

**Comment by alex-konovalov** [comment]
@FriedrichRober is grape needed to use your package, or only to construct examples for some tests? What I can see in your https://github.com/FriedrichRober/LINS/blob/master/PackageInfo.g does not exactly correspond to the way of specifying dependencies on GAP packages, as documented at https://github.com/gap-packages/example/blob/master/PackageInfo.g. The `ExternalConditions` component is for "external" conditions which are outside GAP. For a GAP package, you need to use `NeededOtherPackages` or `SuggestedOtherPackages` if a package relies on that at runtime. If, however, you need it only for a test, and do not want to introduce a dependency otherwise, you can try to load it in a test file, and maybe check if it was loaded before running the relevant example.

**Comment by FriedrichRober** [comment]
Indeed, I only need `grape` for a test and not for the actual algorithm in this package.
This is the reason why I did not want to add it as a dependency in `NeededOtherPackages` or `SuggestedOtherPackages` and thought that it would fit best under `ExternalConditions`.

I asked this, since I needed to specify the following line in my `.travis.yml` file, otherwise the tests would fail:
https://github.com/FriedrichRober/LINS/blob/3fb55378e008512a7096035c551daccf219dab12/.travis.yml#L8

I can try to check if the package `grape` is a loaded before running dependent tests as a workaround for the moment.

**Comment by alex-konovalov** [comment]
@FriedrichRober thanks for details - in this case you do not need in dependencies, but cal load it in a test, if it is available. The line setting `GAP_PKGS_TO_BUILD` is OK, it builds grape in your Travis CI tests. Tests from gap-infra will not use your `.travis.yml` at all, but they run using GAP Docker container, which already included all packages prebuilt, so grape will be there. So most likely everything will work straightforwardly.

**Comment by FriedrichRober** [comment]
@alex-konovalov, thanks for your explanation. I submitted the pull requests [stable-4.11](https://github.com/gap-infra/gap-docker-pkg-tests-stable-4.11-devel/pull/7) and [master](https://github.com/gap-infra/gap-docker-pkg-tests-master-devel/pull/27)

**Comment by alex-konovalov** [comment]
Great, thanks! If you have other packages with tests, please do the same when they're ready.
