### ISSUE TITLE
List package at https://gap-packages.github.io/

### ISSUE THREAD

**Issue by alex-konovalov** [FriedrichRober/LINS#27]
We maintain a list of GAP packages with their public repositories at https://gap-packages.github.io/ - would you like this package to be listed there? It's not limited to packages redistributed with GAP - the aim is to list all packages independently of their status. This will help other GAP users and developers to find them.

**Comment by FriedrichRober** [comment]
Ok, if the status does not matter, we could list this package there. The reason why I did not consider this, is that I want to drastically change the inteface for the users, see #18 . I just need to find time to actually do this, which is quite difficult.

**Comment by alex-konovalov** [comment]
Thanks, That's fine - and clear looking at the package that it's no releases, website etc., so in early development. Done in https://github.com/gap-packages/gap-packages.github.io/commit/dcd0406a692bcc1cfec58148e201c6163db6654b.
